# Generated by Django 5.2 on 2025-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_comment_time_alter_post_time_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('type_of_news', models.CharField(max_length=200)),
                ('description', models.CharField(default=None, max_length=500)),
                ('date', models.IntegerField(null=True)),
                ('time', models.CharField(default='28 April 2025', max_length=100000)),
                ('image', models.ImageField(upload_to='img/news')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='28 April 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='28 April 2025', max_length=100),
        ),
    ]
