# Generated by Django 5.2 on 2025-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_news_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='29 April 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(default='29 April 2025', max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='29 April 2025', max_length=100),
        ),
    ]
